# CHANGES: [2.2] added AUTO_MOVE, ENABLE_MOTORS, MOVE_COOLDOWN_SEC, MOVE_THRESHOLD_MM
COLOR_TOPIC = "/camera/camera/color/image_raw"
DEPTH_TOPIC = "/camera/camera/aligned_depth_to_color/image_raw"
CAMERA_INFO_TOPIC = "/camera/camera/color/camera_info"

DETECTION_MODE = "white_rectangle"
YOLO_MODEL = "yolo11n.pt"
YOLO_IMGSZ = 1280
YOLO_IOU = 0.45
YOLO_MAX_DET = 20
YOLO_DEVICE = "cpu"
CONF_THRES = 0.25
TARGET_CLASS = None
VIEW_IMAGE = True
DRAW_CAMERA_AXIS_LEGEND = False
DRAW_BASE_AXIS_OVERLAY = False
DRAW_DETECTION_CONTOUR = False
DRAW_DETECTION_CORNERS = False
DRAW_OBJECT_SIZE_LABEL = False
REQUIRE_FULL_BBOX_IN_FRAME = True
FRAME_MARGIN_PX = 12
DETECT_ONLY_IN_WORKSPACE = False
DRAW_REJECTED_DETECTIONS = True
BBOX_LABEL = "box"
BBOX_FRAME_MIN_AREA = 2500.0
BBOX_FRAME_MAX_AREA_RATIO = 0.70
BBOX_FRAME_MIN_WIDTH_PX = 60
BBOX_FRAME_MIN_HEIGHT_PX = 40
BBOX_NMS_IOU = 0.35
CANNY_LOW = 60
CANNY_HIGH = 180

WHITE_RECT_MIN_AREA_PX = 600.0
WHITE_RECT_MAX_AREA_RATIO = 0.12
WHITE_RECT_MIN_WIDTH_PX = 24
WHITE_RECT_MIN_HEIGHT_PX = 24
WHITE_RECT_MIN_BRIGHTNESS = 165
WHITE_RECT_MAX_SATURATION = 100
WHITE_RECT_MIN_CONTRAST = 18.0
WHITE_RECT_MASK_OPEN_PX = 3
WHITE_RECT_MASK_CLOSE_PX = 7
WHITE_RECT_BORDER_REJECT_PX = 10
WHITE_RECT_POLY_EPSILON_SCALE = 0.05
WHITE_RECT_MIN_RECTANGULARITY = 0.76
WHITE_RECT_MIN_ASPECT_RATIO = 1.05
WHITE_RECT_MAX_ASPECT_RATIO = 4.50
WHITE_RECT_SUBPIX_WINDOW = 5

PLANE_HOMOGRAPHY_ENABLE = False
PLANE_HOMOGRAPHY_MATRIX = (
    (1.0, 0.0, 0.0),
    (0.0, 1.0, 0.0),
    (0.0, 0.0, 1.0),
)

RECT_POSE_ENABLE = False
RECT_REAL_WIDTH_MM = 0.0
RECT_REAL_HEIGHT_MM = 0.0

WORKSPACE_ROI_ENABLE = False
WORKSPACE_MARGIN_X_PX = 80
WORKSPACE_MARGIN_Y_PX = 80
ROBOT_EXCLUDE_ENABLE = False
ROBOT_EXCLUDE_POLYGONS_NORM = (
    ((0.02, 0.00), (0.12, 0.00), (0.56, 0.28), (0.50, 0.40), (0.40, 0.34)),
    ((0.88, 0.00), (0.98, 0.00), (0.60, 0.34), (0.50, 0.40), (0.44, 0.28)),
    ((0.42, 0.30), (0.58, 0.30), (0.63, 0.58), (0.58, 0.82), (0.42, 0.82), (0.37, 0.58)),
)
ROBOT_EXCLUDE_MAX_BBOX_OVERLAP = 0.12
ROBOT_EXCLUDE_MAX_CONTOUR_OVERLAP = 0.08
DRAW_ROBOT_EXCLUDE = False
FOREGROUND_FLOOR_DEPTH_M = 0.870
FOREGROUND_FLOOR_PERCENTILE = 80.0
FOREGROUND_BG_CLOSE_PX = 41
FOREGROUND_MASK_OPEN_PX = 5
FOREGROUND_MASK_CLOSE_PX = 11
FOREGROUND_MIN_HEIGHT_M = 0.008
FOREGROUND_MAX_HEIGHT_M = 0.200
FOREGROUND_MIN_AREA_PX = 3000.0
FOREGROUND_MAX_AREA_RATIO = 0.50
FOREGROUND_MIN_WIDTH_PX = 60
FOREGROUND_MIN_HEIGHT_PX = 40
FOREGROUND_REQUIRE_BOX_LIKE = True
FOREGROUND_BORDER_REJECT_PX = 30
FOREGROUND_MAX_ASPECT_RATIO = 4.0


BOX_ONLY_ENABLE = True
BOX_ROI_SHRINK = 0.20
BOX_MIN_CONTOUR_AREA = 80.0
BOX_POLY_EPSILON_SCALE = 0.04
BOX_MIN_RECTANGULARITY = 0.72
BOX_MAX_ASPECT_RATIO = 3.0

AVG_FRAME_COUNT = 7
CENTER_WINDOW = 5
TRACK_GRID_PX = 80
DETECTION_CONFIRM_FRAMES = 2
DETECTION_LOST_RESET_FRAMES = 5

STABLE_THRESH_X_MM = 1.5
STABLE_THRESH_Y_MM = 1.5
STABLE_THRESH_Z_MM = 2.0

DEPTH_MIN_M = 0.001
DEPTH_MAX_M = 1.00
DEPTH_BOX_SCALE = 0.35
DEPTH_MIN_VALID_PIXELS = 20
DEPTH_USE_CONTOUR_MASK = True
DEPTH_CONTOUR_ERODE_PX = 5
DEPTH_TRIM_LOW_PERCENT = 25.0
DEPTH_TRIM_HIGH_PERCENT = 75.0
DEPTH_MAD_SCALE = 2.0
DEPTH_HISTORY_SIZE = 7
DEPTH_MAX_JUMP_M = 0.015

FK_VERIFY_TOL_MM = 3.0
PRINT_COOLDOWN_SEC = 1.0
FAKE_MOVE_COOLDOWN_SEC = 1.0
AUTO_MOVE = True
ENABLE_MOTORS = True
MOVE_COOLDOWN_SEC = 1.5
MOVE_THRESHOLD_MM = 4.0

FAKE_DEPTH_ENABLE = False
FAKE_DEPTH_M = 0.30

VISION_ONLY_ENABLE = True
SIMPLE_RESULT_PRINT = True
PURE_CAMERA_TEST_ENABLE = True

CAMERA_TRANSFORM_MODE = "A"
CAMERA_USE_DIRECT_MATRIX = True
CAMERA_DIRECT_MATRIX = (
    (1.0, 0.0, 0.0),
    (0.0, -1.0, 0.0),
    (0.0, 0.0, -1.0),
)
CAM_FINE_ROLL_DEG = 0.0
CAM_FINE_PITCH_DEG = 0.0
CAM_FINE_YAW_DEG = 0.0
CAM_TX_MM = 97.59
CAM_TY_MM = 11.93
CAM_TZ_MM = 432.00

X_LIMIT = 151.563
Y_LIMIT = 151.563
Z_MIN = -500.0
Z_MAX = -196.875

THETA1_MIN = 0.0
THETA1_MAX = 82.11
THETA2_MIN = 0.0
THETA2_MAX = 85.49
THETA3_MIN = 0.0
THETA3_MAX = 85.49
